
	i18n_dict = {
		"add_component" : "Add component",
		"confirm_elimina_componente" : "Pay attention:\nIf you select the option 'Single', all the data of the Group will be deleted.\n\nDo you want to proceed?",
      "mandatory" : "Required field",
        "campo_obbligatorio" : "Required field",
        "numero_non_valido" : "Invalid number",
        "numero_di {0} cifre" : "Must be {0} digits",
        "nuovo_criterio" : "New criterium",
        "e_necessario_compilare_prima_la_denominazione" : "Please, fill out the 'name of the group' field",
        "lbl_text_attribute_type" : "Text",
        "lbl_select_attribute_type" : "List of options",
        "lbl_numeric_attribute_type" : "Number",
        "lbl_boolean_attribute_type" : "Yes/No",
        "lbl_currency_attribute_type" : "Amount",
        "lbl_sp_tech_visibility" : "Technical offer",
        "lbl_sp_financial_visibility" : "Economic offer",
        "lbl_sp_*_visibility" : "Both offers",
        "yes" : "Yes",
        "no" : "No",
        "sono_presenti_errori_gara" : "There are some errors in the tender data.\nDo you still want to approve the publication?",
        "stato_gara_impostato_in_bozza" : "Continuing with the changes, the tender status will be set to \"Draft \" and it will be necessary to request approval for publication.",
        "sono_presenti_errori_schede_prodotto" : "There are some errors in the configuration of the product sheets.\nDo you still want to approve the publication?",
        "lbl_sp_edit" : "Edit",
        "lbl_sp_elimina" : "Delete",
        "lbl_sp_visualizza" : "View",
        "lbl_sp_scheda_prodotto" : "Technical data sheet",
        "lbl_sp_opzioni" : "Options",
        "lbl_sp_opzione" : "Option",
        "lbl_sp_nessun_prodotto" : "No products added",
        "lbl_sp_inserisci_prodotto" : "Add a product",
        "lbl_sp_unica_opzione" : "Only one option can be entered for this tab",
        "lbl_sp_eliminazione_scheda" : "Are you sure to proceed with deleting the sheet?",
        "lbl_sp_crea_modifica_opzione" : "Create/edit purchase option",
        "lbl_sp_descrizione" : "Description",
        "lbl_sp_descrizione_non_valida" : "Invalid description: sheet's description is mandatory.",
        "lbl_sp_dati_non_validi" : "The data entered is not valid.",
        "lbl_sp_salva" : "Save",
        "lbl_sp_chiudi" : "Close",
        "lbl_msp_salvataggio_in_corso" : "Saving in progress",
        "lbl_msp_caricamento_in_corso" : "Loading",
        "lbl_msp_salvataggio_completato" : "Saved",
        "lbl_msp_verificato_errore" : "A server error has occurred. Unable to save changes.",
        "lbl_msp_modifica_scheda" : "Edit Product Sheet",
        "lbl_msp_nuova_scheda" : "New Product Sheet",
        "lbl_msp_nome" : "Name",
        "lbl_msp_nome_non_valido" : "Invalid Sheet Name: The sheet name is required and must be at least",
        "lbl_msp_lettere" : "chars",
        "lbl_msp_permetti_multipli" : "Allow multiple entries",
        "lbl_msp_indietro" : "Back",
        "lbl_msp_salva" : "Save",
        "lbl_msp_dati_modificati_persi" : "If you proceed, the unsaved data will be lost. Continue?",
        "lbl_msp_nessuna_scheda" : "No product data sheet inserted",
        "lbl_msp_multipla" : "Multiple",
        "lbl_msp_attributi" : "Attributes",
        "lbl_msp_modifica" : "Edit",
        "lbl_msp_elimina" : "Delete",
        "lbl_msp_almeno_un_attributo" : "At least one attribute must be entered",
        "lbl_msp_eliminazione_scheda" : "Are you sure you want to delete the card?",
        "lbl_msp_descrizione" : "Description",
        "lbl_msp_visibilita" : "Select visibility",
        "lbl_msp_obligatorio" : "Required",
        "lbl_msp_predefinito" : "Default",
        "lbl_msp_tipo" : "Type",
        "lbl_msp_elenco_schede" : "Product Sheets List",
        "lbl_msp_nuovo_attributo" : "New attribute",
        "lbl_msp_modifica_attributo" : "Change Attribute",
        "lbl_msp_nome_attributo_non_valido" : "Invalid Attribute Name: The attribute name is required and must be at list",
        "lbl_msp_inserire_descrizione" : "Enter a description for the attribute to make it easier for participants to fill in",
        "lbl_msp_opzioni" : "Options",
        "lbl_msp_campo_obbligatorio" : "Required field",
        "lbl_msp_opzione" : "Option",
        "lbl_msp_lista_almeno_un_opzione" : "For the type 'List of options' you must enter at least one option",
        "lbl_msp_valore_predefinito" : "Default value",
        "lbl_msp_valore_non_valido" : "Invalid value",
        "lbl_msp_annulla" : "Cancel",
        "lbl_msp_valore_predefinito_numerico" : "The default value must be numeric.",
        "lbl_msp_nessun_attributo_inserito" : "No attribute entered",
        "lbl_msp_popover_salva" : "To save you need to go back to the Sheets List.",
        "lbl_csp_seleziona_scheda" : "Select Sheet",
        "lbl_csp_filtra_risultati" : "Filter results",
        "lbl_csp_parametro" : "Parameter",
        "lbl_csp_raggruppa" : "Group by",
        "lbl_csp_tutti" : "All",
        "lbl_csp_elenco_schede" : "Sheets List",
        "lbl_csp_nessun_risultato" : "No result",
        "lbl_csp_nessun_selezione" : "Selection",
        "lbl_csp_righe_selezionate" : "selected rows",
        "lbl_csp_compara_selezionati" : "Compare selected",
        "lbl_csp_mostra_tutti" : "Show all",
        "lbl_csp_raggruppati_per" : "Grouped by",
        "lbl_csp_filtrato_per" : "Filtered by",
        "lbl_csp_operatore" : "Operator",
        "lbl_smtp_torna_elenco" : "Back to List",
        "lbl_smtp_seleziona" : "Visibility",
        "lbl_smtp_ricarca_descrizione" : "Search by Description",
        "lbl_smtp_ricerca_onwner" : "Search by Visibility",
        "lbl_smtp_reset_filters" : "Reset Filters",
        "lbl_smtp_nome" : "Name",
        "lbl_smtp_cognome" : "Lastname",
        "lbl_smtp_descrizione" : "Description",/*
        "lbl_smtp_nome_obbligatorio" : "Il nome dell'SMTP deve contenere almeno 4 caratteri e i caratteri ammessi sono: lettere minuscole, '-' e '_'",*/
        "lbl_smtp_host" : "Host",
        "lbl_smtp_formato_mail_vuoto" : "Required field",
        "lbl_smtp_porta" : "Port",
        "lbl_smtp__host_obbligatorio" : "Required field",
        "lbl_smtp__porta_obbligatorio" : "Required field",
        "lbl_smtp_obbligatorio" : "Required",/*
        "lbl_smtp_sicurezza_connessione" : "Sicurezza Connessione",
        "lbl_smtp_submiterror" : "Errore nel Form",
        "lbl_smtp_completa_selezione" : "Completa la selezione",
        "lbl_smtp_email_obbligatoria" : "E-mail Obbligatoria",
        "lbl_smtp_errore_generico" : "Errore generico",
        "lbl_smtp_indirizzo_non_verificato" : "Indirizzo non verificato",
        "lbl_smtp_indirizzo_verificato" : "Indirizzo Verificato",
        "lbl_smtp_generic_error" : "Errore generico",
        "lbl_smtp_salvataggio_in_corso" : "Salvataggio in corso",
        "lbl_smtp_salvato_correttamente" : "Elemento salvato correttamente",
        "lbl_smtp_error" : "Error",
        "lbl_error_saving" : "Errore salvataggio",
        "lbl_smtp_verifing" : "Verifica in corso",
        "lbl_smtp_formato_mail_non_valido" : "Formato mail non valido",*/
        "lbl_smtp_edit" : "Edit",
        "lbl_smtp_verify" : "Verify",
        "lbl_smtp_add_smtp" : "Add Smtp",
        "lbl_smtp_delete" : "Delete",
        "lbl_smtp_is_pec" : "Pec",/*
        "lbl_smtp_formato_password_non_valido" : "Formato Password non valido",
        "lbl_smtp_formato_password_vuoto" : "Campo obbligatorio",
        "lbl_smtp_owner_personale" : "Visibility Personale",*/
        "lbl_smtp_owner" : "Visibility",
        "lbl_smtp_actions" : "Actions",/*
        "lbl_smtp_description_obbligatorio" : "La descrizione deve essere una stringa di almeno 7 caratteri",*/
        "lbl_smtp_pec_all" : "All",
        "lbl_smtp_pec_si" : "Pec YES",
        "lbl_smtp_pec_no" : "Pec NO",

        "lbl_criteri_formula_calcolo" : "Formula for the calculation",
        "lbl_criteri_compilare_campo" : "this field must be completed",
        "lbl_criteri_punteggio_minimo_zero" : "the minimum score must be 0",
        "lbl_criteri_ammesse_solo" : "It's allowed only",
        "lbl_criteri_cifre_decimali" : "decimal digits.",
        "lbl_criteri_superato_valore_massimo" : "you have exceeded the maximum allowed value",
        "lbl_criteri_valore_minimo" : "Minimum allowed value",
        "lbl_criteri_valore_massimo" : "Maximum allowed value",
        "lbl_criteri_solo_interi" : "only whole numbers are allowed",
        "lbl_criteri_punteggio_massimo_inferiore_minimo" : "the maximum score cannot be less than or equal to the minimum",
        "lbl_criteri_punteggio_massimo" : "Maximum attributable score",
        "lbl_criteri_risposta" : "Answer",
        "lbl_criteri_punteggio" : "Score",
        "lbl_criteri_minimo" : "minimum",
        "lbl_criteri_caratteri" : "characters.",
        "lbl_criteri_punteggio_minimo" : "minimumm score",
        "lbl_criteri_aggiungi_opzione" : "+ Add option",
        "lbl_criteri_valore_minimo_range" : "Minimum value",
        "lbl_criteri_valore_massimo_range" : "Maximum value",
        "lbl_criteri_valore_compreso" : "value between",
        "lbl_criteri_e" : "and",
        "lbl_criteri_valore_punteggio" : "the score value must be greater than or equal to zero.",
        "lbl_criteri_loading" : "Loading...",
        "lbl_criteri_domanda" : "Question",
        "lbl_criteri_almeno_3_caratteri" : "at least 3 characters must be entered",
        "lbl_criteri_formato_risposta" : "Reply format",
        "lbl_criteri_salva" : "Save",
        "lbl_criteri_chiudi" : "Cancel",
        "lbl_criteri_formula_calcolo_help" : "for more details click here",
        "lbl_criteri_salvataggio_in_corso" : "Saving in progress...",
        "lbl_criteri_modifiche_salvate" : "Changes saved successfully",
        "lbl_criteri_non_e_possibile_salvare" : "Changes cannot be saved",
        "lbl_criteri_correggere_errori" : "The errors must be corrected in order to save",
        "lbl_criteri_campi_obbligatori" : "required fields",
		"lbl_criteri_punteggio_minimo_ribasso" : "the minimum score that can be attributed must be greater than 0",
        "ad_lbl_invite_counter_main_and_secondary_category_selection_dialog" : "Categories Selection",
        "ad_lbl_invite_counter_no_supply_typology_selected_error" : "No Type of supply selected. Select a type of supply",
        
        "lbl_ws_app_vue_contracting_authority" : "Institution",
        "lbl_ws_app_vue_service" : "Service",
        "lbl_ws_app_vue_tender_type" : "Type",
        "lbl_ws_app_vue_status" : "Status",
        "lbl_ws_app_vue_cig" : "Cig",
        "lbl_gare_pubbliche_filter_oggetto_cig" : "Subject/CIG",/*
        "lbl_gare_pubbliche_bandi_gara" : "Bandi di gara",
        "lbl_ws_app_vue_referrer_office" : "Centro di costo",
        "lbl_ws_app_vue_subject" : "Oggetto",
        "lbl_ws_app_vue_criterion" : "Criterio di aggiudicazione",
        "lbl_ws_app_vue_total_amount" : "Importo complessivo a base d'asta",
        "lbl_ws_app_vue_amount" : "Importo complessivo a base d'asta",
        "lbl_ws_app_vue_base_amount" : "Importo al netto di oneri di sicurezza, manodopera, e iva soggetto a ribasso",
        "lbl_ws_app_vue_base_total_amount" : "Importo a base d'asta",
        "lbl_ws_app_vue_security_charges" : "Oneri Sicurezza (Iva esclusa)",
        "lbl_ws_app_vue_manpower_charges" : "Importo Manodopera non soggetto a ribasso",
        "lbl_ws_app_vue_modalita_gara" : "Modalità di espletamento della gara",
        "lbl_ws_app_vue_publication_date" : "Data pubblicazione",
        "lbl_ws_app_vue_expiration_date" : "Data scadenza",
        "lbl_ws_app_vue_aggiudicatari" : "Aggiudicatari",
        "lbl_ws_app_vue_durata_accordo_quadro" : "Durata dell'accordo quadro",
        "lbl_ws_app_vue_security_charges" : "Oneri Sicurezza da interferenze (Iva esclusa)",
        "lbl_ws_app_vue_question_submission_deadline" : "Termine ultimo per la presentazione di quesiti",
        "lbl_ws_app_vue_tender_documents" : "Documentazione gara",
        "lbl_ws_app_vue_admin_documents_requested" : "Documentazione amministrativa richiesta",
        "lbl_ws_app_vue_stampa_riepilogo" : "Stampa riepilogo",
        "lbl_ws_app_vue_documents_tab_publications" : "Pubblicazioni",
        "lbl_ws_app_vue_tender_documents" : "Documentazione gara",
        "lbl_ws_app_vue_cerca" : "Cerca",
        "lbl_ws_app_vue_reset" : "Reset",
        "lbl_ws_app_vue_dettagli" : "Dettagli",
        "lbl_ws_app_vue_back" : "Torna indietro",
        "lbl_ws_app_vue_first" : "Prima",
        "lbl_ws_app_vue_last" : "Ultima",
        "lbl_ws_app_vue_next" : "Avanti",
        "lbl_ws_app_vue_previous" : "Indietro",
        "lbl_ws_app_vue_base_total_amount" : "Importo a base d'asta",
        "lbl_ws_app_vue_percentuale_ribasso" : "Ribasso offerto",
        "lbl_ws_app_vue_documenti" : "Documenti",
        "lbl_ws_app_vue_documentazione" : "Documentazione",
        "lbl_ws_app_vue_documentazione_richiesta" : "Documentazione richiesta",
        "lbl_ws_app_vue_documentazione_amministrativa" : "Documentazione amministrativa richiesta",
        "lbl_ws_app_vue_documentazione_economica" : "Documentazione economica richiesta",
        "lbl_ws_app_vue_documentazione_tecnica" : "Documentazione tecnica richiesta",
        "lbl_ws_app_vue_pubblicazioni" : "Pubblicazioni",
        "lbl_ws_app_vue_pubblicazioni_no_data" : "Non è presente alcun documento in questa sezione.",
        "lbl_ws_app_vue_pubblicazioni_title" : "pubblicazioni ai sensi dell'art. 29 d.lgs. 50/2016",
        "lbl_ws_app_vue_no_data" : "Nessun dato trovato",
        "lbl_ws_app_vue_denominazione" : "Denominazione",
        "lbl_ws_app_vue_vat_number" : "Partita iva",
        "lbl_ws_app_vue_chiudi" : "Chiudi",
        "lbl_ws_app_vue_no_fac_simile" : "Fac-simile non disponibile",
        "lbl_ws_app_vue_tipo_fornitura" : "Tipo di fornitura",
        "lbl_ws_app_vue_tender_id_code" : "CIG",
        "lbl_ws_app_vue_cup_number" : "CUP",
        "lbl_ws_app_vue_closed_message_label" : "Motivazione",
        "lbl_ws_app_vue_awarded_user" : "Aggiudicatario",
        "lbl_ws_app_vue_ask_more_info_to" : "Per richiedere informazioni",
        "lbl_ws_app_vue_more_information" : "Riepilogo informazioni",
        "lbl_ws_app_vue_from" : "Da",
        "lbl_ws_app_vue_to" : "A",

        "lbl_esiti_title_tender_results" : "Esiti di gare e affidamenti",
        "lbl_esiti_tender_type" : "Tipologia di gara",
        "lbl_esiti_awarded_user" : "Aggiudicatario",
        "lbl_esiti_awarded_users" : "Aggiudicatari",
        "lbl_esiti_awarded_users_date" : "aggiudicato il",
        "lbl_esiti_award_date" : "Data aggiudicazione",
        "lbl_esiti_amount" : "Importo soggetto a ribasso",
        "lbl_esiti_award_amount" : "Importo Aggiudicazione",
        "lbl_esiti_invitati_partecipanti" : "Invitati/Partecipanti",
        "lbl_esiti_durata_aq" : "Durata dell'accordo quadro",
        "lbl_esiti_bando" : "Bando",
        "lbl_esiti_operatori_invitati" : "Operatori invitati a partecipare alla procedura",
        "lbl_esiti_partecipanti" : "Partecipanti",
        "lbl_esiti_no_invitati_partecipanti" : "Nessun invitato/partecipante",
        "lbl_no_items_found" : "Nessun elemento trovato",

        "lbl_modifica_lotti_edit_parts" : "Modifica veloce lotti",
        "lbl_modifica_lotti_index" : "Lotto",
        "lbl_modifica_lotti_oggetto" : "Oggetto",
        "lbl_modifica_lotti_cig" : "Cig",
        "lbl_modifica_lotti_importo_complessivo" : "Importo complessivo a base d'asta",
        "lbl_modifica_lotti_importo_soggetto_ribasso" : "Importo soggetto a ribasso",
        "lbl_modifica_lotti_oneri_non_soggetti_ribasso" : "Oneri non soggetti a ribasso",
        "lbl_modifica_lotti_cauzione" : "Garanzia fidejussoria",
        "lbl_modifica_lotti_importo_contributo_anac" : "Importo contributo ANAC",
        "lbl_modifica_lotti_importo_cauzione" : "Importo cauzione",
        "lbl_modifica_lotti_back" : "Indietro",
        "lbl_modifica_lotti_save" : "Salva",
        "lbl_modifica_lotti_salvataggio_in_corso" : "Salvataggio in corso",
        "lbl_modifica_lotti_caricamento_in_corso" : "Caricamento in corso",
        "lbl_modifica_lotti_salvataggio_completato" : "Salvataggio completato",
        "lbl_modifica_lotti_verificato_errore" : "Si è verificato un errore nel server. Impossibile salvare le modifiche.",
        "lbl_modifica_lotti_cig_already_used_error" : "Cig già in uso",
        "lbl_modifica_lotti_cig_error" : "Il cig deve essere di 10 caratteri alfanumerici",
        "lbl_modifica_lotti_required_error" : "Campo obbligatorio",
        "lbl_modifica_lotti_decimal_error" : "Formato non corretto",

        "lbl_simog_filter_user_by_username_label" : "Filtra per nome utente",
        "lbl_simog_filter_reset_label" : "Resetta filtri",
        "lbl_simog_user_manage_username_label" : "Nome Utente",
        "lbl_simog_user_manage_name_label" : "Utente",
        "lbl_simog_user_manage_actions_label" : "Azioni",
        "lbl_simog_get_user_list_error_label" : "Errore durante il recupero della lista degli utenti abilitati dal WS del Simog",
        "lbl_simog_add_user_error_label" : "Errore durante l'aggiunta dell'utente alla lista degli abilitati con WS del Simog",
        "lbl_simog_remove_user_error_label" : "Errore durante l'eliminazione dell'utente alla lista degli abilitati con WS del Simog",
        "lbl_simog_generic_error_label" : "Errore durante l'esecuzione dell'operazione richiesta",
        "lbl_simog_generic_success_label" : "Operazione eseguita con successo",
        "lbl_simog_generic_operation_label" : "Operazione in corso",

        "lbl_smartcig_filter_user_by_username_label" : "Filtra per nome utente",
        "lbl_smartcig_filter_reset_label" : "Resetta filtri",
        "lbl_smartcig_user_manage_username_label" : "Nome Utente",
        "lbl_smartcig_user_manage_name_label" : "Utente",
        "lbl_smartcig_user_manage_actions_label" : "Azioni",
        "lbl_smartcig_get_user_list_error_label" : "Errore durante il recupero della lista degli utenti abilitati dal WS dello SmartCIG",
        "lbl_smartcig_add_user_error_label" : "Errore durante l'aggiunta dell'utente alla lista degli abilitati con WS dello SmartCIG",
        "lbl_smartcig_remove_user_error_label" : "Errore durante l'eliminazione dell'utente alla lista degli abilitati con WS dello SmartCIG",
        "lbl_smartcig_generic_error_label" : "Errore durante l'esecuzione dell'operazione richiesta",
        "lbl_smartcig_generic_success_label" : "Operazione eseguita con successo",
        "lbl_smartcig_generic_operation_label" : "Operazione in corso",

        "lbl_message_state_conferma_1" : "Invio messaggio confermato",
        "lbl_message_state_accettazione_1" : "Invio messaggio accettato",
        "lbl_message_state_accettazione_non-verificato" : "Invio messaggio non verificato",
        "lbl_supplier_validated_title" : "Riepilogo dettagli messaggio",
        "lbl_imap_notify_title_status" : "Stato messaggio",
        "lbl_imap_notify_id_lbl" : "Id invio messaggio",
        "lbl_imap_notify_status_lbl" : "Stato invio messaggio",
        "lbl_imap_notify_date_lbl" : "Data invio messaggio",
        "lbl_imap_notify_accettazione" : "Accettato",
        "lbl_imap_notify_email_deleted" : "Messaggio cancellato",
        "lbl_imap_notify_email_credentials_error" : "Credenziali imap errate",
        "lbl_imap_notify_non-accettazione" : "Non accettato",
        "lbl_imap_notify_presa-in-carico" : "Presa in carico",
        "lbl_imap_notify_avvenuta-consegna" : "Avvenuta consegna",
        "lbl_imap_notify_posta-certificata" : "Posta certificata",
        "lbl_imap_notify_errore-consegna" : "Errore consegna",
        "lbl_imap_notify_preavviso-errore-consegna" : "Preavviso errore consegna",
        "lbl_imap_notify_rilevazione-virus" : "Rilevazione virus",
        "lbl_smtp_imap_enable" : "Abilita configurazione imap",
        "lbl_smtp_imap_host" : "Host",
        "lbl_smtp_imap_porta" : "Porta",
        "lbl_smtp_imap_sicurezza_connessione" : "Sicurezza connessione",
        "lbl_smtp_imap_use_smtp_credentials" : "Utilizza le stesse credenzali smtp",*/
        "lbl_smtp_imap_username" : "Username",
        "lbl_smtp_imap_password" : "Password",
        "lbl_smtp_imap_all" : "All",
        "lbl_smtp_imap_si" : "IMAP YES",
        "lbl_smtp_imap_no" : "IMAP NO",
				"lbl_imap_is_check" : "IMAP control",
				
				"lbl_verbali_action" : "Change status",
        "lbl_verbali_ignora_messaggi_commissione" : "Ignore messages between commission members",
        "lbl_verbali_action_genera_verbale" : "Generate chat minutes",
        "lbl_verbali_form_range_date" : "Select time frame",
        "lbl_verbali_action_visibile" : "Visible message",
        "lbl_verbali_action_omissis" : "Omissis message",
        "lbl_verbali_action_escluso" : "Message not visible",
        "lbl_verbali_form_tipo_sistema" : "System message",
        "lbl_verbali_form_tipo_membro_commissione" : "Message sent by: remote commissioner",
        "lbl_verbali_form_tipo_commissione" : "Message sent from: Commission",
        "lbl_verbali_form_tipo_operatore_economico" : "Message sent by: economic operator",
        "lbl_verbali_form_tipo_null" : "Message sent by: all",
        "lbl_verbali_form_stato_null" : "All messages",
        "lbl_verbali_form_cerca" : "Search...",
        "lbl_verbali_form_cerca_titolo" : "Search filters",
        "lbl_verbali_action_reset_filters" : "Reset filters",
        "lbl_verbali_messaggio" : "Message",
        "lbl_verbali_inviato_da" : "Sent by",
        "lbl_verbali_azioni" : "Actions",
        "lbl_verbali_visibilita" : "Visibility",
        "lbl_verbali_no_results" : "No search results for messages",        
        "Email non valida" : "Invalid e-mail",
        "Partita Iva non valida" : "Invalid VAT number",
        "Denominazione non valida" : "Invalid company name",

        "lbl_criteri_lista_scelte" : "List of choices",
        "lbl_criteri_numero_intero" : "Whole number",
        "lbl_criteri_numero_decimale" : "Decimal number",
        "lbl_criteri_percentuale" : "Percentage",
        "lbl_criteri_proporzionalita_inversa_ribasso" : "Inverse proportionality on the downside",
        "lbl_criteri_proporzionalita_inversa_rialzo" : "Inverse proportionality to the upside",
        "lbl_criteri_min_max_range" : "Minimum - maximum range",
        "Scheda Prodotto" : "Product Sheet",
        "Operatore" : "Supplier",
        "lbl_sdg_lista_partecipanti" : "Back to the list",

        "lbl_importa_da_metaprodotto" : "Import from product sheet",
        "lbl_seleziona_categoria" : "Select category",
        "lbl_seleziona_metaprodotto" : "Select product sheet",

        "lbl_smtp_change_password" : "Change password",

        "lbl_smtp_id" : "Id",
        "lbl_smtp_email" : "E-mail",
        "lbl_smtp_server_username" : "Username",

    };
	$.i18n.load(i18n_dict);